### ISSUE TITLE
Cannot install: uninitialized constant Homebrew::YAML

### ISSUE THREAD

**Issue by pudge** [dracula/macos-color-picker#3]
Odd error. I tried removing the Dracula tap/cask and reinstalling.

```
$ brew tap dracula/install
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 114 (delta 21), reused 34 (delta 17), pack-reused 68
Receiving objects: 100% (114/114), 21.55 KiB | 1.96 MiB/s, done.
Resolving deltas: 100% (43/43), done.
Tapped 1 command, 13 casks and 1 formula (32 files, 52.0KB).

$ brew install --cask dracula-macos-color-picker
==> Downloading https://github.com/dracula/macos-color-picker/archive/refs/heads/main.zip
==> Downloading from https://codeload.github.com/dracula/macos-color-picker/zip/refs/heads/main
#-=#=-  #     #
Warning: No checksum defined for cask 'dracula-macos-color-picker', skipping verification.
==> Installing Cask dracula-macos-color-picker
/opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:51:in `dracula_yaml_json': uninitialized constant Homebrew::YAML (NameError)
	from ./generate.command:6:in `<main>'
==> Purging files for version latest of Cask dracula-macos-color-picker
Error: It seems the Generic Artifact source '/opt/homebrew/Caskroom/dracula-macos-color-picker/latest/macos-color-picker-main/Dracula.clr' is not there.
```

**Comment by konniemommy** [comment]
```
brew update && brew upgrade && brew cleanup
brew untap dracula/install --force
brew tap dracula/install
brew install --cask dracula-macos-color-picker
Already up-to-date.
Untapping dracula/install...
Untapped 1 command, 13 casks and 1 formula (34 files, 53.8KB).
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 114, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 114 (delta 21), reused 34 (delta 17), pack-reused 68
Receiving objects: 100% (114/114), 21.55 KiB | 218.00 KiB/s, done.
Resolving deltas: 100% (43/43), done.
Tapped 1 command, 13 casks and 1 formula (33 files, 52.6KB).
==> Downloading https://github.com/dracula/macos-color-picker/archive/refs/heads/main.zip
==> Downloading from https://codeload.github.com/dracula/macos-color-picker/zip/refs/heads/main
  -#O=#    #     #                                                                                                
Warning: No checksum defined for cask 'dracula-macos-color-picker', skipping verification.
==> Installing Cask dracula-macos-color-picker
/opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:51:in `dracula_yaml_json': uninitialized constant Homebrew::YAML (NameError)
	from ./generate.command:6:in `<main>'
==> Purging files for version latest of Cask dracula-macos-color-picker
Error: It seems the Generic Artifact source '/opt/homebrew/Caskroom/dracula-macos-color-picker/latest/macos-color-picker-main/Dracula.clr' is not there.
```

**Comment by norbertpunk** [comment]
~ % brew tap dracula/install                      
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 142 (delta 33), reused 50 (delta 23), pack-reused 68
Receiving objects: 100% (142/142), 28.37 KiB | 2.18 MiB/s, done.
Resolving deltas: 100% (55/55), done.
Tapped 1 command, 15 casks and 1 formula (34 files, 61.8KB).
~ % brew install --cask dracula-macos-color-picker
==> Downloading https://github.com/dracula/macos-color-picker/archive/refs/heads/main.zip
Warning: No checksum defined for cask 'dracula-macos-color-picker', skipping verification.
==> Installing Cask dracula-macos-color-picker
/opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:5:in `require': cannot load such file -- active_support/all (LoadError)
	from /opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:5:in `<top (required)>'
	from ./generate.command:4:in `require'
	from ./generate.command:4:in `<main>'
==> Purging files for version latest of Cask dracula-macos-color-picker
Error: It seems the Generic Artifact source '/opt/homebrew/Caskroom/dracula-macos-color-picker/latest/macos-color-picker-main/Dracula.clr' is not there.
